function(argos_enable_sanitizers target)
    if(MSVC)
        if(ARGOS_ENABLE_ASAN)
            target_compile_options(${target} PRIVATE /fsanitize=address)
        endif()
        return()
    endif()

    if(ARGOS_ENABLE_TSAN AND (ARGOS_ENABLE_ASAN OR ARGOS_ENABLE_UBSAN))
        message(FATAL_ERROR "TSan must run in a separate build from ASan/UBSan")
    endif()

    set(sanitizers "")
    if(ARGOS_ENABLE_ASAN)
        list(APPEND sanitizers "address")
    endif()
    if(ARGOS_ENABLE_UBSAN)
        list(APPEND sanitizers "undefined")
    endif()
    if(ARGOS_ENABLE_TSAN)
        list(APPEND sanitizers "thread")
    endif()

    if(sanitizers)
        list(JOIN sanitizers "," sanitizer_flags)
        target_compile_options(${target} PRIVATE -fsanitize=${sanitizer_flags} -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=${sanitizer_flags})
    endif()
endfunction()
